package com.musiclibrary.new_model;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.Set;
import java.util.HashSet;
import java.util.List;
import java.util.ArrayList;

/**
 * Enhanced Playlist Model Class
 * 
 * Represents a comprehensive user-created playlist with advanced features,
 * collaboration capabilities, and detailed analytics.
 * 
 * Key Enhancements:
 * - Advanced sharing and collaboration features
 * - Smart playlist algorithms and auto-generation
 * - Detailed user engagement analytics
 * - Social features (following, likes, comments)
 * - Advanced categorization and mood-based organization
 * - Playlist versioning and history tracking
 * - Integration with streaming platforms and export capabilities
 * 
 * @author Music Library Development Team
 * @version 2.0
 * @since Java 8+
 */
public class Playlist {
    
    // Primary Identifiers
    private Long playlistId;
    private String playlistName;
    private String slug;                    // URL-friendly identifier
    private String uuid;                    // Universal unique identifier
    
    // Basic Information
    private String description;
    private String shortDescription;        // Brief summary
    private Long creatorId;                 // User who created playlist
    private String creatorName;
    private String creatorDisplayName;
    
    // Content Organization
    private List<Long> songIds;             // Ordered list of songs
    private List<Integer> songPositions;    // Track positions for reordering
    private Set<String> genres;             // Predominant genres
    private Set<String> moods;              // Emotional categorization
    private Set<String> activities;         // Workout, Study, Party, etc.
    private Set<String> tags;               // User-defined tags
    
    // Playlist Metadata
    private Integer songCount;
    private Duration totalDuration;
    private Double averageEnergy;           // Average energy of songs
    private Double averageDanceability;
    private Double averageValence;          // Overall mood positivity
    private String dominantGenre;
    private String overallMood;
    
    // Visibility and Sharing
    private String visibility;              // Public, Private, Unlisted, Friends
    private Boolean isCollaborative;        // Allow others to edit
    private Set<Long> collaboratorIds;      // Users who can edit
    private Set<String> collaboratorNames;
    private Boolean allowComments;
    private Boolean allowLikes;
    private String shareCode;               // Unique code for sharing
    
    // Social Engagement
    private Long likeCount;
    private Long shareCount;
    private Long followCount;               // Users following this playlist
    private Long playCount;
    private Long uniqueListeners;
    private Double engagementRate;
    private LocalDateTime lastPlayed;
    private String lastPlayedBy;
    
    // Smart Playlist Features
    private Boolean isSmartPlaylist;        // Auto-generated/updated
    private String smartCriteria;           // JSON criteria for auto-generation
    private LocalDateTime lastAutoUpdate;
    private Boolean autoUpdate;             // Keep updating automatically
    private Integer maxSongs;               // Limit for smart playlists
    
    // Platform Integration
    private String spotifyId;               // Spotify playlist ID
    private String appleMusicId;
    private String youTubeMusicId;
    private String soundCloudId;
    private Boolean syncWithSpotify;
    private Boolean syncWithAppleMusic;
    
    // Categorization and Discovery
    private String category;                // Pop, Rock, Classical, etc.
    private String subCategory;
    private String targetAudience;          // Kids, Teens, Adults, etc.
    private String occasion;                // Birthday, Wedding, Holiday
    private String season;                  // Spring, Summer, Fall, Winter
    private String timeOfDay;               // Morning, Afternoon, Evening, Night
    private Integer recommendedAge;         // Recommended minimum age
    
    // Performance and Analytics
    private Double averageRating;
    private Integer totalRatings;
    private Long totalShuffles;             // How often played on shuffle
    private Double skipRate;                // Percentage of songs skipped
    private Double completionRate;          // How often played fully
    private Duration averageSessionTime;    // Average listening session
    private String mostPlayedSong;
    private String leastPlayedSong;
    
    // Image and Media
    private String coverImageUrl;
    private String bannerImageUrl;
    private String customArtUrl;            // User-uploaded cover
    private Boolean useAutoGeneratedCover;  // Use algorithm-generated cover
    
    // Export and Backup
    private String lastExportFormat;        // M3U, CSV, JSON, etc.
    private LocalDateTime lastExportDate;
    private String backupLocation;
    private Boolean autoBackup;
    private Integer backupFrequencyDays;
    
    // Versioning and History
    private Integer version;
    private LocalDateTime lastModified;
    private String lastModifiedBy;
    private Integer changeCount;            // Number of modifications
    private String changeLog;               // Summary of recent changes
    private Boolean trackChanges;           // Keep history of changes
    
    // Recommendations and Similar Content
    private Set<Long> similarPlaylistIds;   // Similar playlists
    private Set<String> recommendedGenres;
    private Set<Long> recommendedSongIds;   // Songs to potentially add
    private Double recommendationScore;     // Algorithm confidence
    
    // Commercial and Legal
    private Boolean isOfficial;             // Created by artist/label
    private String sponsorship;             // Sponsored content info
    private Boolean hasExplicitContent;
    private String contentWarning;
    private String licenseType;
    private Boolean commercialUse;
    
    // Location and Context
    private String createdLocation;         // Where playlist was created
    private String lastPlayedLocation;
    private Set<String> popularRegions;     // Where playlist is popular
    private String timezone;
    
    // Advanced Features
    private Boolean isFeatured;             // Featured by platform
    private String featuredReason;
    private LocalDateTime featuredDate;
    private Boolean isEditorial;            // Curated by editors
    private String editorialNote;
    private Boolean isGenerated;            // Algorithm-generated
    private String generationSource;        // What triggered generation
    
    // User Preferences
    private Boolean allowDownloads;         // If users can download
    private Boolean allowOfflineSync;       // Allow offline listening
    private String qualityPreference;       // Audio quality setting
    private Boolean shuffleByDefault;       // Default to shuffle mode
    private Boolean repeatEnabled;          // Allow repeat
    
    // Audit Information
    private LocalDateTime createdDate;
    private String createdBy;
    private String createdFromDevice;       // Device/app used to create
    private String createdFromLocation;
    
    /**
     * Default constructor
     */
    public Playlist() {
        this.songIds = new ArrayList<>();
        this.songPositions = new ArrayList<>();
        this.genres = new HashSet<>();
        this.moods = new HashSet<>();
        this.activities = new HashSet<>();
        this.tags = new HashSet<>();
        this.collaboratorIds = new HashSet<>();
        this.collaboratorNames = new HashSet<>();
        this.similarPlaylistIds = new HashSet<>();
        this.recommendedGenres = new HashSet<>();
        this.recommendedSongIds = new HashSet<>();
        this.popularRegions = new HashSet<>();
        
        this.createdDate = LocalDateTime.now();
        this.lastModified = LocalDateTime.now();
        this.version = 1;
        this.visibility = "Private";
        this.isCollaborative = false;
        this.allowComments = true;
        this.allowLikes = true;
        this.isSmartPlaylist = false;
        this.autoUpdate = false;
        this.syncWithSpotify = false;
        this.syncWithAppleMusic = false;
        this.useAutoGeneratedCover = true;
        this.autoBackup = false;
        this.backupFrequencyDays = 30;
        this.trackChanges = true;
        this.isOfficial = false;
        this.hasExplicitContent = false;
        this.commercialUse = false;
        this.isFeatured = false;
        this.isEditorial = false;
        this.isGenerated = false;
        this.allowDownloads = false;
        this.allowOfflineSync = true;
        this.shuffleByDefault = false;
        this.repeatEnabled = true;
        this.songCount = 0;
        this.likeCount = 0L;
        this.shareCount = 0L;
        this.followCount = 0L;
        this.playCount = 0L;
        this.uniqueListeners = 0L;
        this.engagementRate = 0.0;
        this.averageRating = 0.0;
        this.totalRatings = 0;
        this.totalShuffles = 0L;
        this.skipRate = 0.0;
        this.completionRate = 0.0;
        this.recommendationScore = 0.0;
        this.changeCount = 0;
    }
    
    // Getters and Setters
    
    public Long getPlaylistId() { return playlistId; }
    public void setPlaylistId(Long playlistId) { this.playlistId = playlistId; }
    
    public String getPlaylistName() { return playlistName; }
    public void setPlaylistName(String playlistName) { this.playlistName = playlistName; }
    
    public String getSlug() { return slug; }
    public void setSlug(String slug) { this.slug = slug; }
    
    public String getUuid() { return uuid; }
    public void setUuid(String uuid) { this.uuid = uuid; }
    
    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
    
    public String getShortDescription() { return shortDescription; }
    public void setShortDescription(String shortDescription) { this.shortDescription = shortDescription; }
    
    public Long getCreatorId() { return creatorId; }
    public void setCreatorId(Long creatorId) { this.creatorId = creatorId; }
    
    public String getCreatorName() { return creatorName; }
    public void setCreatorName(String creatorName) { this.creatorName = creatorName; }
    
    public String getCreatorDisplayName() { return creatorDisplayName; }
    public void setCreatorDisplayName(String creatorDisplayName) { this.creatorDisplayName = creatorDisplayName; }
    
    public List<Long> getSongIds() { return songIds; }
    public void setSongIds(List<Long> songIds) { this.songIds = songIds; }
    
    public List<Integer> getSongPositions() { return songPositions; }
    public void setSongPositions(List<Integer> songPositions) { this.songPositions = songPositions; }
    
    public Set<String> getGenres() { return genres; }
    public void setGenres(Set<String> genres) { this.genres = genres; }
    
    public Set<String> getMoods() { return moods; }
    public void setMoods(Set<String> moods) { this.moods = moods; }
    
    public Set<String> getActivities() { return activities; }
    public void setActivities(Set<String> activities) { this.activities = activities; }
    
    public Set<String> getTags() { return tags; }
    public void setTags(Set<String> tags) { this.tags = tags; }
    
    public Integer getSongCount() { return songCount; }
    public void setSongCount(Integer songCount) { this.songCount = songCount; }
    
    public Duration getTotalDuration() { return totalDuration; }
    public void setTotalDuration(Duration totalDuration) { this.totalDuration = totalDuration; }
    
    public Double getAverageEnergy() { return averageEnergy; }
    public void setAverageEnergy(Double averageEnergy) { this.averageEnergy = averageEnergy; }
    
    public Double getAverageDanceability() { return averageDanceability; }
    public void setAverageDanceability(Double averageDanceability) { this.averageDanceability = averageDanceability; }
    
    public Double getAverageValence() { return averageValence; }
    public void setAverageValence(Double averageValence) { this.averageValence = averageValence; }
    
    public String getDominantGenre() { return dominantGenre; }
    public void setDominantGenre(String dominantGenre) { this.dominantGenre = dominantGenre; }
    
    public String getOverallMood() { return overallMood; }
    public void setOverallMood(String overallMood) { this.overallMood = overallMood; }
    
    public String getVisibility() { return visibility; }
    public void setVisibility(String visibility) { this.visibility = visibility; }
    
    public Boolean getIsCollaborative() { return isCollaborative; }
    public void setIsCollaborative(Boolean isCollaborative) { this.isCollaborative = isCollaborative; }
    
    public Set<Long> getCollaboratorIds() { return collaboratorIds; }
    public void setCollaboratorIds(Set<Long> collaboratorIds) { this.collaboratorIds = collaboratorIds; }
    
    public Set<String> getCollaboratorNames() { return collaboratorNames; }
    public void setCollaboratorNames(Set<String> collaboratorNames) { this.collaboratorNames = collaboratorNames; }
    
    public Boolean getAllowComments() { return allowComments; }
    public void setAllowComments(Boolean allowComments) { this.allowComments = allowComments; }
    
    public Boolean getAllowLikes() { return allowLikes; }
    public void setAllowLikes(Boolean allowLikes) { this.allowLikes = allowLikes; }
    
    public String getShareCode() { return shareCode; }
    public void setShareCode(String shareCode) { this.shareCode = shareCode; }
    
    public Long getLikeCount() { return likeCount; }
    public void setLikeCount(Long likeCount) { this.likeCount = likeCount; }
    
    public Long getShareCount() { return shareCount; }
    public void setShareCount(Long shareCount) { this.shareCount = shareCount; }
    
    public Long getFollowCount() { return followCount; }
    public void setFollowCount(Long followCount) { this.followCount = followCount; }
    
    public Long getPlayCount() { return playCount; }
    public void setPlayCount(Long playCount) { this.playCount = playCount; }
    
    public Long getUniqueListeners() { return uniqueListeners; }
    public void setUniqueListeners(Long uniqueListeners) { this.uniqueListeners = uniqueListeners; }
    
    public Double getEngagementRate() { return engagementRate; }
    public void setEngagementRate(Double engagementRate) { this.engagementRate = engagementRate; }
    
    public LocalDateTime getLastPlayed() { return lastPlayed; }
    public void setLastPlayed(LocalDateTime lastPlayed) { this.lastPlayed = lastPlayed; }
    
    public String getLastPlayedBy() { return lastPlayedBy; }
    public void setLastPlayedBy(String lastPlayedBy) { this.lastPlayedBy = lastPlayedBy; }
    
    public Boolean getIsSmartPlaylist() { return isSmartPlaylist; }
    public void setIsSmartPlaylist(Boolean isSmartPlaylist) { this.isSmartPlaylist = isSmartPlaylist; }
    
    public String getSmartCriteria() { return smartCriteria; }
    public void setSmartCriteria(String smartCriteria) { this.smartCriteria = smartCriteria; }
    
    public LocalDateTime getLastAutoUpdate() { return lastAutoUpdate; }
    public void setLastAutoUpdate(LocalDateTime lastAutoUpdate) { this.lastAutoUpdate = lastAutoUpdate; }
    
    public Boolean getAutoUpdate() { return autoUpdate; }
    public void setAutoUpdate(Boolean autoUpdate) { this.autoUpdate = autoUpdate; }
    
    public Integer getMaxSongs() { return maxSongs; }
    public void setMaxSongs(Integer maxSongs) { this.maxSongs = maxSongs; }
    
    public String getSpotifyId() { return spotifyId; }
    public void setSpotifyId(String spotifyId) { this.spotifyId = spotifyId; }
    
    public String getAppleMusicId() { return appleMusicId; }
    public void setAppleMusicId(String appleMusicId) { this.appleMusicId = appleMusicId; }
    
    public String getYouTubeMusicId() { return youTubeMusicId; }
    public void setYouTubeMusicId(String youTubeMusicId) { this.youTubeMusicId = youTubeMusicId; }
    
    public String getSoundCloudId() { return soundCloudId; }
    public void setSoundCloudId(String soundCloudId) { this.soundCloudId = soundCloudId; }
    
    public Boolean getSyncWithSpotify() { return syncWithSpotify; }
    public void setSyncWithSpotify(Boolean syncWithSpotify) { this.syncWithSpotify = syncWithSpotify; }
    
    public Boolean getSyncWithAppleMusic() { return syncWithAppleMusic; }
    public void setSyncWithAppleMusic(Boolean syncWithAppleMusic) { this.syncWithAppleMusic = syncWithAppleMusic; }
    
    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }
    
    public String getSubCategory() { return subCategory; }
    public void setSubCategory(String subCategory) { this.subCategory = subCategory; }
    
    public String getTargetAudience() { return targetAudience; }
    public void setTargetAudience(String targetAudience) { this.targetAudience = targetAudience; }
    
    public String getOccasion() { return occasion; }
    public void setOccasion(String occasion) { this.occasion = occasion; }
    
    public String getSeason() { return season; }
    public void setSeason(String season) { this.season = season; }
    
    public String getTimeOfDay() { return timeOfDay; }
    public void setTimeOfDay(String timeOfDay) { this.timeOfDay = timeOfDay; }
    
    public Integer getRecommendedAge() { return recommendedAge; }
    public void setRecommendedAge(Integer recommendedAge) { this.recommendedAge = recommendedAge; }
    
    public Double getAverageRating() { return averageRating; }
    public void setAverageRating(Double averageRating) { this.averageRating = averageRating; }
    
    public Integer getTotalRatings() { return totalRatings; }
    public void setTotalRatings(Integer totalRatings) { this.totalRatings = totalRatings; }
    
    public Long getTotalShuffles() { return totalShuffles; }
    public void setTotalShuffles(Long totalShuffles) { this.totalShuffles = totalShuffles; }
    
    public Double getSkipRate() { return skipRate; }
    public void setSkipRate(Double skipRate) { this.skipRate = skipRate; }
    
    public Double getCompletionRate() { return completionRate; }
    public void setCompletionRate(Double completionRate) { this.completionRate = completionRate; }
    
    public Duration getAverageSessionTime() { return averageSessionTime; }
    public void setAverageSessionTime(Duration averageSessionTime) { this.averageSessionTime = averageSessionTime; }
    
    public String getMostPlayedSong() { return mostPlayedSong; }
    public void setMostPlayedSong(String mostPlayedSong) { this.mostPlayedSong = mostPlayedSong; }
    
    public String getLeastPlayedSong() { return leastPlayedSong; }
    public void setLeastPlayedSong(String leastPlayedSong) { this.leastPlayedSong = leastPlayedSong; }
    
    public String getCoverImageUrl() { return coverImageUrl; }
    public void setCoverImageUrl(String coverImageUrl) { this.coverImageUrl = coverImageUrl; }
    
    public String getBannerImageUrl() { return bannerImageUrl; }
    public void setBannerImageUrl(String bannerImageUrl) { this.bannerImageUrl = bannerImageUrl; }
    
    public String getCustomArtUrl() { return customArtUrl; }
    public void setCustomArtUrl(String customArtUrl) { this.customArtUrl = customArtUrl; }
    
    public Boolean getUseAutoGeneratedCover() { return useAutoGeneratedCover; }
    public void setUseAutoGeneratedCover(Boolean useAutoGeneratedCover) { this.useAutoGeneratedCover = useAutoGeneratedCover; }
    
    public String getLastExportFormat() { return lastExportFormat; }
    public void setLastExportFormat(String lastExportFormat) { this.lastExportFormat = lastExportFormat; }
    
    public LocalDateTime getLastExportDate() { return lastExportDate; }
    public void setLastExportDate(LocalDateTime lastExportDate) { this.lastExportDate = lastExportDate; }
    
    public String getBackupLocation() { return backupLocation; }
    public void setBackupLocation(String backupLocation) { this.backupLocation = backupLocation; }
    
    public Boolean getAutoBackup() { return autoBackup; }
    public void setAutoBackup(Boolean autoBackup) { this.autoBackup = autoBackup; }
    
    public Integer getBackupFrequencyDays() { return backupFrequencyDays; }
    public void setBackupFrequencyDays(Integer backupFrequencyDays) { this.backupFrequencyDays = backupFrequencyDays; }
    
    public Integer getVersion() { return version; }
    public void setVersion(Integer version) { this.version = version; }
    
    public LocalDateTime getLastModified() { return lastModified; }
    public void setLastModified(LocalDateTime lastModified) { this.lastModified = lastModified; }
    
    public String getLastModifiedBy() { return lastModifiedBy; }
    public void setLastModifiedBy(String lastModifiedBy) { this.lastModifiedBy = lastModifiedBy; }
    
    public Integer getChangeCount() { return changeCount; }
    public void setChangeCount(Integer changeCount) { this.changeCount = changeCount; }
    
    public String getChangeLog() { return changeLog; }
    public void setChangeLog(String changeLog) { this.changeLog = changeLog; }
    
    public Boolean getTrackChanges() { return trackChanges; }
    public void setTrackChanges(Boolean trackChanges) { this.trackChanges = trackChanges; }
    
    public Set<Long> getSimilarPlaylistIds() { return similarPlaylistIds; }
    public void setSimilarPlaylistIds(Set<Long> similarPlaylistIds) { this.similarPlaylistIds = similarPlaylistIds; }
    
    public Set<String> getRecommendedGenres() { return recommendedGenres; }
    public void setRecommendedGenres(Set<String> recommendedGenres) { this.recommendedGenres = recommendedGenres; }
    
    public Set<Long> getRecommendedSongIds() { return recommendedSongIds; }
    public void setRecommendedSongIds(Set<Long> recommendedSongIds) { this.recommendedSongIds = recommendedSongIds; }
    
    public Double getRecommendationScore() { return recommendationScore; }
    public void setRecommendationScore(Double recommendationScore) { this.recommendationScore = recommendationScore; }
    
    public Boolean getIsOfficial() { return isOfficial; }
    public void setIsOfficial(Boolean isOfficial) { this.isOfficial = isOfficial; }
    
    public String getSponsorship() { return sponsorship; }
    public void setSponsorship(String sponsorship) { this.sponsorship = sponsorship; }
    
    public Boolean getHasExplicitContent() { return hasExplicitContent; }
    public void setHasExplicitContent(Boolean hasExplicitContent) { this.hasExplicitContent = hasExplicitContent; }
    
    public String getContentWarning() { return contentWarning; }
    public void setContentWarning(String contentWarning) { this.contentWarning = contentWarning; }
    
    public String getLicenseType() { return licenseType; }
    public void setLicenseType(String licenseType) { this.licenseType = licenseType; }
    
    public Boolean getCommercialUse() { return commercialUse; }
    public void setCommercialUse(Boolean commercialUse) { this.commercialUse = commercialUse; }
    
    public String getCreatedLocation() { return createdLocation; }
    public void setCreatedLocation(String createdLocation) { this.createdLocation = createdLocation; }
    
    public String getLastPlayedLocation() { return lastPlayedLocation; }
    public void setLastPlayedLocation(String lastPlayedLocation) { this.lastPlayedLocation = lastPlayedLocation; }
    
    public Set<String> getPopularRegions() { return popularRegions; }
    public void setPopularRegions(Set<String> popularRegions) { this.popularRegions = popularRegions; }
    
    public String getTimezone() { return timezone; }
    public void setTimezone(String timezone) { this.timezone = timezone; }
    
    public Boolean getIsFeatured() { return isFeatured; }
    public void setIsFeatured(Boolean isFeatured) { this.isFeatured = isFeatured; }
    
    public String getFeaturedReason() { return featuredReason; }
    public void setFeaturedReason(String featuredReason) { this.featuredReason = featuredReason; }
    
    public LocalDateTime getFeaturedDate() { return featuredDate; }
    public void setFeaturedDate(LocalDateTime featuredDate) { this.featuredDate = featuredDate; }
    
    public Boolean getIsEditorial() { return isEditorial; }
    public void setIsEditorial(Boolean isEditorial) { this.isEditorial = isEditorial; }
    
    public String getEditorialNote() { return editorialNote; }
    public void setEditorialNote(String editorialNote) { this.editorialNote = editorialNote; }
    
    public Boolean getIsGenerated() { return isGenerated; }
    public void setIsGenerated(Boolean isGenerated) { this.isGenerated = isGenerated; }
    
    public String getGenerationSource() { return generationSource; }
    public void setGenerationSource(String generationSource) { this.generationSource = generationSource; }
    
    public Boolean getAllowDownloads() { return allowDownloads; }
    public void setAllowDownloads(Boolean allowDownloads) { this.allowDownloads = allowDownloads; }
    
    public Boolean getAllowOfflineSync() { return allowOfflineSync; }
    public void setAllowOfflineSync(Boolean allowOfflineSync) { this.allowOfflineSync = allowOfflineSync; }
    
    public String getQualityPreference() { return qualityPreference; }
    public void setQualityPreference(String qualityPreference) { this.qualityPreference = qualityPreference; }
    
    public Boolean getShuffleByDefault() { return shuffleByDefault; }
    public void setShuffleByDefault(Boolean shuffleByDefault) { this.shuffleByDefault = shuffleByDefault; }
    
    public Boolean getRepeatEnabled() { return repeatEnabled; }
    public void setRepeatEnabled(Boolean repeatEnabled) { this.repeatEnabled = repeatEnabled; }
    
    public LocalDateTime getCreatedDate() { return createdDate; }
    public void setCreatedDate(LocalDateTime createdDate) { this.createdDate = createdDate; }
    
    public String getCreatedBy() { return createdBy; }
    public void setCreatedBy(String createdBy) { this.createdBy = createdBy; }
    
    public String getCreatedFromDevice() { return createdFromDevice; }
    public void setCreatedFromDevice(String createdFromDevice) { this.createdFromDevice = createdFromDevice; }
    
    public String getCreatedFromLocation() { return createdFromLocation; }
    public void setCreatedFromLocation(String createdFromLocation) { this.createdFromLocation = createdFromLocation; }
    
    // Utility Methods
    
    public void touch() {
        this.lastModified = LocalDateTime.now();
        this.version++;
        this.changeCount++;
    }
    
    public void addSong(Long songId) {
        if (songIds == null) songIds = new ArrayList<>();
        songIds.add(songId);
        songCount = songIds.size();
    }
    
    public void removeSong(Long songId) {
        if (songIds != null) {
            songIds.remove(songId);
            songCount = songIds.size();
        }
    }
    
    public void addCollaborator(Long userId, String userName) {
        if (collaboratorIds == null) collaboratorIds = new HashSet<>();
        if (collaboratorNames == null) collaboratorNames = new HashSet<>();
        collaboratorIds.add(userId);
        collaboratorNames.add(userName);
    }
    
    public Integer getTotalDurationSeconds() {
        return totalDuration != null ? (int) totalDuration.getSeconds() : null;
    }
    
    public void setTotalDurationSeconds(Integer seconds) {
        this.totalDuration = seconds != null ? Duration.ofSeconds(seconds) : null;
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Playlist playlist = (Playlist) o;
        return Objects.equals(playlistId, playlist.playlistId);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(playlistId);
    }
    
    @Override
    public String toString() {
        return "Playlist{" +
                "playlistId=" + playlistId +
                ", playlistName='" + playlistName + '\'' +
                ", creatorName='" + creatorName + '\'' +
                ", songCount=" + songCount +
                ", visibility='" + visibility + '\'' +
                ", isCollaborative=" + isCollaborative +
                '}';
    }
}
